/** `data-qa` values for the signup forms, used with `cy.getByQa()`. */
export const registrationSelectors = {
  signupNameInput: 'signup-name',
  signupEmailInput: 'signup-email',
  signupButton: 'signup-button',
  /** Wraps both title radios; the radio is picked by its form value (Mr / Mrs). */
  titleGroup: 'title',
  passwordInput: 'password',
  birthDaySelect: 'days',
  birthMonthSelect: 'months',
  birthYearSelect: 'years',
  firstNameInput: 'first_name',
  lastNameInput: 'last_name',
  companyInput: 'company',
  address1Input: 'address',
  address2Input: 'address2',
  countrySelect: 'country',
  stateInput: 'state',
  cityInput: 'city',
  zipcodeInput: 'zipcode',
  mobileNumberInput: 'mobile_number',
  createAccountButton: 'create-account',
  accountCreatedHeading: 'account-created',
  continueButton: 'continue-button',
} as const;
