import { Then, When } from '@badeball/cypress-cucumber-preprocessor';
import { checkoutComponent } from '../components/checkout.component';
import { buildTestCard } from '../data/payment.factory';
import { payOrder, proceedToCheckout } from '../flows/checkout.flow';
import { requireRegisteredUser, type ScenarioWorld } from '../world';

When('the customer proceeds to checkout', () => {
  proceedToCheckout();
});

When('the customer pays for the order with a test card', function (this: ScenarioWorld) {
  payOrder('Order generated by the E2E suite', buildTestCard(requireRegisteredUser(this).name));
});

Then("the delivery address matches the customer's profile", function (this: ScenarioWorld) {
  checkoutComponent.expectDeliveryAddress(requireRegisteredUser(this).profile);
});

Then('the order is confirmed', () => {
  checkoutComponent.expectOrderPlaced();
});
