import { appConfig } from '../config';
import type { ContactMessage } from '../types/contact';

export function buildContactMessage(): ContactMessage {
  const { name, emailDomain } = appConfig().contact;
  const uniqueId = `${Date.now()}${Cypress._.random(1000, 9999)}`;
  return {
    name,
    email: `qa.contact.${uniqueId}@${emailDomain}`,
    subject: `Test inquiry ${uniqueId}`,
    message: 'Message generated by the E2E suite. Please ignore.',
  };
}
