import type { ContactMessage } from '../types/contact';

export function buildContactMessage(): ContactMessage {
  const uniqueId = `${Date.now()}${Cypress._.random(1000, 9999)}`;
  return {
    name: 'QA Visitor',
    email: `qa.contact.${uniqueId}@example.com`,
    subject: `Test inquiry ${uniqueId}`,
    message: 'Message generated by the E2E suite. Please ignore.',
  };
}
